// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Game = {
  id: number,
  p1: Identity,
  p2: Identity,
  result: number,
  when: Timestamp,
  ready1: boolean,
  ready2: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Game {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("p1", AlgebraicType.createIdentityType()),
      new ProductTypeElement("p2", AlgebraicType.createIdentityType()),
      new ProductTypeElement("result", AlgebraicType.createU8Type()),
      new ProductTypeElement("when", AlgebraicType.createTimestampType()),
      new ProductTypeElement("ready1", AlgebraicType.createBoolType()),
      new ProductTypeElement("ready2", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Game): void {
    Game.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Game {
    return Game.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


